"""empty message

Revision ID: 745c44dcd0fc
Revises: 9e0e482ac222
Create Date: 2023-12-07 21:06:51.280384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '745c44dcd0fc'
down_revision: Union[str, None] = '9e0e482ac222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matches', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_results')
    # ### end Alembic commands ###
