"""empty message

Revision ID: d394a321531a
Revises: 56ff02d48584
Create Date: 2023-12-06 16:49:03.640924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd394a321531a'
down_revision: Union[str, None] = '56ff02d48584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'games', 'players', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'creator_id')
    # ### end Alembic commands ###
